name: Actualitzar Meteocat

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "bot"
          git stash
          git pull --rebase
          git add meteocat.csv last_update.txt
          git diff --cached --quiet || git commit -m "update"
          git push
